---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.redis.name }}-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
