# This is a YAML-formatted file.

image: gitlab.s056568.edu.slurm.io/s056568/application
imageTag: application.latest
#imagePullSecret: flask-app-gitlab-registry
imagePullSecret: registry-credentials

replicas: 1

redis:
  name: redis
  port: 6379
#  pvc: pv1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  port: 5000
  name: flask

ingress:
  host: flask.s056568.edu.slurm.io
  secretName: my-tls

pvc:
  storage: 2Gi
